name: Frontend V2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install
        working-directory: frontend-v2

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HCP_UW }}'
          channelId: v2
          projectId: hcp-uw
          entryPoint: frontend-v2
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
